database:
  driverClass: org.postgresql.Driver
  user: unused-user
  password: unused-pw
  url: unused-url

server:
  rootPath: /*
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8081
